### ISSUE TITLE
.NET 9 support

### ISSUE THREAD

**Issue by melwynpkb** [launchdarkly/dotnet-logging-adapter-ms#19]
Hi, could we please extend support to .NET 9 since a RC was released this week?

**Comment by brckelly** [comment]
I think what is meant here is support for Microsoft.Extensions.Logging 9.0.0.  Forcing the update gives this warning:

`NU1608 Detected package version outside of dependency constraint: LaunchDarkly.Logging.Microsoft 3.1.0 requires Microsoft.Extensions.Logging (>= 6.0.0 && < 9.0.0) but version Microsoft.Extensions.Logging 9.0.0 was resolved.`
