### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by omorsky-pcor** [launchdarkly/dotnet-logging-adapter-ms#7]
Hello,
Can I ask for .NET 7 support?

Thanks

**Comment by dantdj** [comment]
I'm attempting to get these changes in as part of #9

**Comment by jbojcic1** [comment]
I really need this too. Can we get the pr from @dantdj merged pls?

**Comment by dantdj** [comment]
It looks like the sole contributor to this repo left LaunchDarkly, so I don't have high hopes - might be worth forking your own copy and making the changes

**Comment by jbojcic1** [comment]
I ended up just copying the code since it's just one file anyway

**Comment by kinyoklion** [comment]
Released in 3.1
